# Generated by Django 5.0.4 on 2024-05-24 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('passWord', models.CharField(max_length=50)),
                ('birth', models.DateField(default='2000-01-01')),
                ('email', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200, null=True)),
                ('phoneNumber', models.CharField(max_length=11, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('Customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Index.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Index.member'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('numbersell', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('Category', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Index.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(blank=True, default=False, null=True)),
                ('transaction_id', models.CharField(max_length=200, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('Customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Index.customer')),
                ('bill', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Index.bill')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Index.product')),
            ],
            options={
                'unique_together': {('product', 'bill')},
            },
        ),
    ]
