# Generated by Django 5.0.4 on 2024-06-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Index", "0004_orders_alter_orderitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="address",
            field=models.CharField(max_length=255),
        ),
    ]
