# Generated by Django 5.0.4 on 2024-06-02 20:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Index", "0005_alter_orders_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="order",
            new_name="orders",
        ),
    ]
